COUNTRIES = [
    "US",
    "ID",
    "TR",
    "JP",
    "TH",
    "RU",
    "MY",
    "BR",
    "SG",
    "PH",
    "BE",
    "KR",
    "GB",
    "MX",
    "DE",
    "FR",
    "ES",
    "CL",
    "UA",
    "IT",
    "CA",
    "AU",
    "SA",
    "CN",
    "HK",
    "FI",
    "NL",
    "TW",
    "AR",
    "GR",
    "CZ",
    "KW",
    "AE",
    "IN",
    "CO",
    "RO",
    "VN",
    "IR",
    "HU",
    "SE",
    "PE",
    "PL",
    "LV",
    "PT",
    "EG",
    "AT",
    "ZA",
    "CH",
    "BY",
    "PY",
    "RS",
    "CR",
    "DK",
    "BG",
    "IE",
    "VE",
    "DO",
    "MV",
    "CY",
    "MK",
    "EE",
    "NZ",
    "PR",
    "BN",
    "HR",
    "NO",
    "SK",
    "IL",
    "EC",
    "MD",
    "PA",
    "LT",
    "GT",
    "KH",
    "QA",
    "BH",
    "AZ",
    "GE",
    "SV",
    "TN",
    "LK",
    "JO",
    "UY",
    "KE",
    "KZ",
    "MQ",
    "LB",
    "MA",
    "IS",
    "HN",
    "SI",
    "MT",
    "GU",
    "ME",
    "OM",
    "BO",
    "TT",
    "LU",
    "JM",
    "PK",
    "BD",
    "XX",
    "MN",
    "AM",
    "TM",
    "MO",
    "LA",
    "NI",
    "BA",
    "KG",
    "NG",
    "BB",
    "UZ",
    "NP",
    "BS",
    "GH",
    "AW",
    "AL",
    "TZ",
    "IQ",
    "IM",
    "UG",
    "MU",
    "VI",
    "MC",
    "GP",
    "SD",
    "XK",
    "KY",
    "ZM",
    "MP",
    "MZ",
    "AX",
    "CU",
    "BM",
    "SY",
    "ET",
    "JE",
    "BZ",
    "SM",
    "LC",
    "GG",
    "VA",
    "BL",
    "TC",
    "CW",
    "AD",
    "RE",
    "PF",
    "SR",
    "GI",
    "BW",
    "AO",
    "HT",
    "FJ",
    "WS",
    "GD",
    "GF",
    "KP",
    "VC",
    "RW",
    "SC",
    "MG",
    "DZ",
    "VG",
    "SX",
    "PS",
    "AF",
    "MF",
    "AG",
    "CM",
    "CI",
    "DM",
    "CD",
    "SN",
    "LI",
    "AQ",
    "MW",
    "TL",
    "BT",
    "CV",
    "KN",
    "BF",
    "AI",
    "SZ",
    "ZW",
    "AN",
    "LY",
    "NC",
    "YE",
    "SO",
    "GA",
    "EU",
    "PM",
    "BI",
    "GL",
    "GM",
    "BV",
    "NE",
    "GW",
    "TJ",
    "BQ",
    "GQ",
    "BJ",
    "TG",
    "ST",
    "VU",
    "PG",
    "PW",
    "TO",
    "SH",
    "GY",
    "SL",
    "YT",
    "FO",
    "DJ",
    "EH",
    "SJ",
    "LR",
    "SS",
    "ZZ",
]

CAT_REGROUP = [
    [
        "airport terminals",
        "airports",
        "airport services",
        "airport lounges",
        "airport food courts",
        "airport ticket counter",
        "airport trams",
        "airfields",
    ],
    ["bus stations", "bus stops"],
    ["opera houses", "concert halls"],
    ["metro stations", "tram stations", "light rail stations", "train stations"],
    [
        "auto garages",
        "auto workshops",
        "automotive shops",
        "auto dealerships",
        "motorcycle shops",
        "new auto dealerships",
    ],
    [
        "hotels",
        "casinos",
        "hotel bars",
        "motels",
        "resorts",
        "residences",
        "inns",
        "hostels",
        "bed breakfasts",
    ],
    [
        "bakeries",
        "borek places",
        "cupcake shops",
        "bagel shops",
        "breakfast spots",
        "gozleme places",
    ],
    [
        "college classrooms",
        "college labs",
        "college science buildings",
        "college arts buildings",
        "college history buildings",
        "college cricket pitches",
        "college communications buildings",
        "college academic buildings",
        "college quads",
        "college auditoriums",
        "college engineering buildings",
        "college math buildings",
        "college bookstores",
        "college technology buildings",
        "college libraries",
        "libraries",
        "college football fields",
        "college administrative buildings",
        "general colleges universities",
        "universities",
        "community colleges",
        "high schools",
        "student centers",
        "college residence halls",
        "schools",
        "private schools",
    ],
    ["movie theaters", "film studios", "indie movie theaters", "multiplexes"],
    [
        "emergency rooms",
        "hospitals",
        "medical centers",
        "hospital wards",
        "medical supply stores",
        "physical therapists",
        "maternity clinics",
        "medical labs",
        "doctor s offices",
    ],
    ["baggage claims", "general travel", "toll plazas"],
    [
        "cafes",
        "dessert shops",
        "donut shops",
        "coffee shops",
        "ice cream shops",
        "corporate coffee shops",
        "coffee roasters",
    ],
    ["hockey arenas", "basketball stadiums", "hockey fields", "hockey rinks"],
    [
        "buildings",
        "offices",
        "coworking spaces",
        "insurance offices",
        "banks",
        "campaign offices",
        "trailer parks",
        "atms",
    ],
    ["capitol buildings", "government buildings", "police stations"],
    ["beach bars", "beaches", "surf spots", "nudist beaches"],
    [
        "asian restaurants",
        "shabu shabu restaurants",
        "noodle houses",
        "chinese restaurants",
        "malay restaurants",
        "sundanese restaurants",
        "cantonese restaurants",
        "chinese breakfast places",
        "ramen restaurants",
        "indonesian restaurants",
        "satay restaurants",
        "javanese restaurants",
        "padangnese restaurants",
        "indonesian meatball places",
    ],
    [
        "historic sites",
        "temples",
        "mosques",
        "spiritual centers",
        "monasteries",
        "churches",
        "history museums",
        "buddhist temples",
        "mountains",
    ],
    ["bars", "pubs"],
    [
        "gyms",
        "gyms or fitness centers",
        "gymnastics gyms",
        "gym pools",
        "yoga studios",
        "badminton courts",
        "courthouses",
    ],
    ["fast food restaurants", "burger joints", "fried chicken joints"],
    [
        "nail salons",
        "salons barbershops",
        "perfume shops",
        "department stores",
        "cosmetics shops",
    ],
    [
        "alternative healers",
        "health beauty services",
        "chiropractors",
        "acupuncturists",
    ],
    ["grocery stores", "health food stores", "supermarkets"],
    ["boutiques", "clothing stores"],
    ["elementary schools", "middle schools"],
    ["electronics stores", "mobile phone shops"],
    ["convenience stores", "truck stops", "gas stations"],
    ["theme park rides attractions", "theme parks"],
    ["outlet malls", "shopping malls", "adult boutiques", "shopping plazas"],
    ["farmers markets", "markets"],
    ["general entertainment", "paintball fields"],
    ["som tum restaurants", "thai restaurants"],
    ["piers", "ports"],
    ["rugby stadiums", "soccer stadiums", "stadiums", "soccer fields"],
    ["lounges", "vape stores"],
    ["massage studios", "spas"],
    ["racecourses", "racetracks"],
    ["men s stores", "women s stores"],
    ["american restaurants", "tex mex restaurants"],
    ["japanese restaurants", "sushi restaurants"],
    ["indian restaurants", "mamak restaurants"],
    ["baseball fields", "baseball stadiums"],
    ["tennis courts", "tennis stadiums"],
    ["drugstores", "pharmacies"],
    ["city halls", "town halls"],
    ["ski areas", "ski chalets", "ski lodges"],
    ["lakes", "reservoirs"],
    ["greek restaurants", "tavernas"],
    ["hills", "scenic lookouts"],
    [
        "college soccer fields",
        "college stadiums",
        "college hockey rinks",
        "college tracks",
        "college basketball courts",
    ],
    ["furniture home stores", "mattress stores", "lighting stores"],
    ["recruiting agencies", "rehab centers"],
    ["art museums", "art studios", "art galleries", "museums", "history museums"],
    ["outdoor supply stores", "sporting goods shops"],
    ["czech restaurants", "restaurants"],
    ["street fairs", "street food gatherings"],
    ["canal locks", "canals"],
    ["sake bars", "soba restaurants"],
    ["bookstores", "newsagents", "newsstands", "stationery stores"],
    ["other great outdoors", "rafting spots"],
    ["manti places", "turkish restaurants"],
    ["shoe repair shops", "shoe stores"],
    ["photography labs", "photography studios"],
    ["bowling alleys", "bowling greens"],
    ["dry cleaners", "laundry services"],
    ["cigkofte places", "kofte places"],
    ["strip clubs", "other nightlife", "gay bars", "nightclubs", "rock clubs"],
    ["dog runs", "parks", "forests", "rv parks", "playgrounds"],
    ["convention centers", "event spaces", "conventions"],
    ["cruise ships", "harbors marinas", "piers", "boats or ferries"],
    ["italian restaurants", "pizza places"],
    ["law schools", "lawyers"],
    ["bubble tea shops", "tea rooms"],
    ["monuments landmarks", "outdoor sculptures"],
    ["beer bars", "beer stores", "beer gardens", "breweries", "brasseries"],
    ["kebab restaurants", "steakhouses"],
    [
        "real estate offices",
        "rental services",
        "rental car locations",
        "residential buildings apartments condos",
    ],
    ["golf courses", "mini golf courses"],
    ["food drink shops", "food services", "food stands", "food trucks"],
    ["salad places", "sandwich places", "shawarma places"],
    ["ski chairlifts", "ski trails", "apres ski bars", "skate parks"],
    ["wine shops", "wineries"],
    ["flea markets", "floating markets"],
    ["burrito places", "taco places"],
    ["pet services", "pet stores", "veterinarians"],
    ["music festivals", "music venues", "music stores", "music schools"],
    ["irish pubs", "pie shops"],
    ["zoo exhibits", "exhibits", "zoos"],
    ["general travel", "bridges"],
    ["sporting goods shops", "athletics & sports", "hunting supplies"],
    ["optical shops", "eye doctors"],
    ["home services & repairs", "other repair shops"],
]


NAME_DI = {
    "uluslararası": "international",
    "havaalani": "airport",
    "havalimani": "airport",
    "stantsiiametro": "metro",
    "aeropuerto": "airport",
    "seveneleven": "7eleven",
    "kfckfc": "kfc",
    "carefour": "carrefour",
    "makdonalds": "mcdonalds",
    "xingbake": "starbucks",
    "mcdonaldss": "mcdonalds",
    "kentuckyfriedchicken": "kfc",
    "restoran": "restaurant",
    "aiport": "airport",
    "terminal": "airport",
    "starbuckscoffee": "starbucks",
    "7elevenechewniielfewn": "7eleven",
    "adtsecurityservices": "adt",
    "ambarrukmoplaza": "ambarukmoplaza",
    "attauthorizedretailer": "att",
    "bandarjakarta": "bandardjakarta",
    "dairyqueenaedriikhwiin": "dairyqueen",
    "dunkindonut": "dunkin",
    "dunkindonuts": "dunkin",
    "dunkindonutsdnkndwnts": "dunkin",
    "ionmoruguichuanzhuchechang": "ionmoruguichuan",
    "tebingkaraton": "tebingkeraton",
    "tebingkraton": "tebingkeraton",
    "711": "7eleven",
    "albertsonspharmacy": "albertsons",
    "applebeesgrillbar": "applebees",
    "attstore": "att",
    "autozoneautoparts": "autozone",
    "awrestaurant": "aw",
    "chilisgrillbar": "chilis",
    "creditrepairservices": "creditrepair",
    "dominospizza": "dominos",
    "firestonecompleteautocare": "firestone",
    "flyingjtravelcenter": "flyingj",
    "libertytaxservice": "libertytax",
    "mcdonald": "mcdonalds",
    "papajohnspizza": "papajohns",
    "pepboysautopartsservice": "pepboys",
    "piatiorochka": "piaterochka",
    "pilottravelcenters": "pilottravelcenter",
    "sainsburyslocal": "sainsburys",
    "sberbankrossii": "sberbank",
    "shellgasstation": "shell",
    "sprintstore": "sprint",
    "strbks": "starbucks",
    "starbucksreserve": "starbucks",
    "usbankbranch": "usbank",
    "verizonauthorizedretailercellularsales": "verizon",
    "verizonwireless": "verizon",
    "vodafonecepmerkezi": "vodafone",
    "vodafoneshop": "vodafone",
    "walmartneighborhoodmarket": "walmart",
    "walmartsupercenter": "walmart",
    "wellsfargobank": "wellsfargo",
    "zaxbyschickenfingersbuffalowings": "zaxbys",
    "ashleyfurniturehomestore": "ashleyhomestore",
    "ashleyfurniture": "ashleyhomestore",
}

CITY_DI = {
    "alkhubar": "alkhobar",
    "khobar": "alkhobar",
    "muratpasa": "antalya",
    "antwerpen": "antwerp",
    "kuta": "badung",
    "bandungregency": "bandung",
    "bengaluru": "bangalore",
    "bkk": "bangkok",
    "krungethphmhaankhr": "bangkok",
    "pattaya": "banglamung",
    "sathon": "bangrak",
    "silom": "bangrak",
    "beijingshi": "beijing",
    "beograd": "belgrade",
    "ratchathewi": "bangkok",
    "brussels": "brussel",
    "bruxelles": "brussel",
    "bucuresti": "bucharest",
    "capitalfederal": "buenosaires",
    "busangwangyeogsi": "busan",
    "cagayandeorocity": "cagayandeoro",
    "cebucity": "cebu",
    "mueangchiangmai": "chiangmai",
    "qianxieshi": "chiba",
    "qiandaitianqu": "chiyoda",
    "zhongyangqu": "chuo",
    "sumedang": "cikeruh",
    "mexico": "ciudaddemexico",
    "mexicocity": "ciudaddemexico",
    "mexicodf": "ciudaddemexico",
    "koln": "cologne",
    "kobenhavn": "copenhagen",
    "osaka": "dabanshibeiqu",
    "jakarta": "dkijakarta",
    "dnipropetrovsk": "dnepropetrovsk",
    "frankfurtammain": "frankfurt",
    "fukuoka": "fugangshi",
    "minato": "gangqu",
    "moscow": "gorodmoskva",
    "moskva": "gorodmoskva",
    "sanktpeterburg": "gorodsanktpeterburg",
    "spb": "gorodsanktpeterburg",
    "hoankiem": "hanoi",
    "yokohama": "hengbangshi",
    "hochiminhcity": "hochiminh",
    "shouye_": "home_",
    "krungethph": "huaikhwang",
    "konak": "izmir",
    "kocaeli": "izmit",
    "jakartacapitalregion": "dkijakarta",
    "southjakarta": "jakartaselatan",
    "shanghai": "jingan",
    "shanghaishi": "jingan",
    "kyoto": "jingdushi",
    "melikgazi": "kayseri",
    "kharkov": "kharkiv",
    "kiyiv": "kiev",
    "kyiv": "kiev",
    "paradise": "lasvegas",
    "lisbon": "lisboa",
    "makaticity": "makati",
    "mandaluyongcity": "mandaluyong",
    "milano": "milan",
    "mingguwushizhongqu": "mingguwushi",
    "nagoyashi": "mingguwushi",
    "munich": "munchen",
    "muntinlupacity": "muntinlupa",
    "pasaycity": "pasay",
    "pasigcity": "pasig",
    "samsennai": "phayathai",
    "praha": "prague",
    "santiagodechile": "santiago",
    "zhahuangshi": "sapporo",
    "seoulteugbyeolsi": "seoul",
    "shenhushizhongyangqu": "shenhushi",
    "shibuya": "shibuiguqu",
    "xinsuqu": "shinjuku",
    "sofiia": "sofia",
    "surakarta": "solo",
    "suwonsi": "suweonsi",
    "taguigcity": "taguig",
    "taipei": "taibeishi",
    "watthana": "vadhana",
    "wien": "vienna",
    "warszawa": "warsaw",
    "washingtondc": "washington",
    "surgutkhantymansiiskiiavtonomnyiokrugiugraaorossiiskaiafederatsiia": "surgut",
    "newyorkcity": "newyork",
    "newyorknyus": "newyork",
    "ny": "newyork",
    "nyc": "newyork",
    "londongreaterlondon": "london",
    "greaterlondon": "london",
    "losangelescaus": "losangeles",
    "dabanshibeiqu": "dabanshi",
    "seoulsi": "seoul",
    "kuwaitcity": "kuwait",
    "bangkoknoi": "bangkok",
}

CITY_DI_2 = {
    "jakartaselatan": "dkijakarta",
    "jakartapusat": "dkijakarta",
    "jakartabarat": "dkijakarta",
    "jakartautara": "dkijakarta",
    "jakartatimur": "dkijakarta",
    "saintpetersburg": "sanktpeterburg",
}

ID_DI = {
    "bandarudara": "airport",
    "bandara": "airport",
    "ruang": "room",
    "smanegeri": "sma",
    "sman": "sma",
    "gedung": "building",
    "danau": "lake",
    "sumatera": "sumatra",
    "utara": "north",
    "barat": "west",
    "jawa": "java",
    "timur": "east",
    "tengah": "central",
    "selatan": "south",
    "kepulauan": "island",
}

LL1 = [
    [
        "starbucks",
        "starbucksstarbucks",
        "staarbakhs",
        "starbuck",
        "starbucksstaarbakhs",
        "sturbucks",
        "starbuckscoffe",
        "starbaks",
        "starbacks",
        "starbuks",
        "starbucksdrivethru",
    ],
    ["walmart", "wallmart", "wallyworld"],
    [
        "mcdonalds",
        "mcdonaldss",
        "macdonalds",
        "makdonals",
        "macdonals",
        "mcdonals",
        "macdonald",
        "mccafe",
        "mcdonaldssmccafe",
        "mcd",
        "mcdonaldssdrivethru",
        "mcdrive",
        "mcdonaldssmaidanglao",
        "mcdonaldssmkdwnldz",
        "mcdonaldssdrive",
        "makdak",
    ],
    ["paylessshoesource", "payless", "paylessshoes"],
    ["savealot", "savelot"],
    ["subway", "subwaysbwy", "subwayrestaurants"],
    ["burgerking", "burguerking"],
    ["pizzahut", "pizzahutdelivery", "pizzahutexpress"],
    ["dunkin", "dunkindnkndwnts"],
    ["firestone", "firestoneautocare"],
    ["dominos", "dominopizza"],
    [
        "uspostoffice",
        "postoffice",
        "unitedstatespostalservice",
        "usps",
        "unitedstatespostoffice",
    ],
    [
        "jcpenney",
        "jcpenny",
        "jcpopticalpopupshop",
        "jcpenneyoptical",
        "jcpenneysalon",
        "jcpennysalon",
        "jcpenneyportraitstudio",
    ],
    ["enterpriserentacar", "enterprise", "enterprisecarvanhire"],
    ["littlecaesarspizza", "littlecaesars", "littleceasars"],
    ["nettomarkendiscount", "nettofiliale", "netto"],
    ["kroger", "krogerfuel", "krogerpharmacy", "krogermarketplace"],
    ["tgifridays", "fridays"],
    ["ngurahraiinternationalairport", "airportngurahrai"],
    ["tangkubanperahu", "tangkubanparahu"],
    [
        "adisuciptointernationalairport",
        "adisuciptoairport",
        "adisutjiptoairport",
        "adisutjiptointernationalairport",
    ],
    ["kualanamuinternationalairport", "kualanamuinternasionalairport"],
    ["esenlerotogar", "esenlerotogari"],
    ["hydepark", "hydeparklondon", "londonhydepark", "hidepark", "haydpark"],
    ["tesco", "tescoexpress"],
    ["gatwickairport", "londongatwickairport", "gatwick", "englandgatwickairport"],
    [
        "heathrowairport",
        "londonheathrowairport",
        "heathrowairportlondon",
        "heathrow",
        "londonheathrowinternationalairport",
        "heatrowairport",
        "londonheathrowairportairport",
        "londonheathrowairportengland",
        "heathrowunitedkingdom",
        "heatrow",
        "lhrairport",
    ],
    [
        "metroadmiralteiskaia",
        "admiralteiskaia",
        "stantsiiametroadmiralteiskaia",
        "admiralteiskaiametro",
        "metroadmiralteiskaiametroadmiralteyskaya",
        "admiralteiskaiastmetro",
    ],
    ["kfc", "kfccoffee", "kfckfc", "kfcdrivethru"],
    ["cvspharmacy", "cvs"],
    ["chasebank", "chase"],
    ["tgifridays", "tgifriday", "tgif"],
    ["costacoffee", "costa"],
    ["jcpenney", "jcpennys"],
    ["santanderbank", "santander", "bancosantander"],
    ["coffeebean", "coffeebeantealeaf", "coffebeantealeaf"],
    [
        "antalyaairport",
        "antalyainternationalairport",
        "antalyaairportairport",
        "antalyaairportayt",
        "antalyadishatlarairporti",
    ],
    [
        "esenbogaairport",
        "ankaraesenbogaairport",
        "esenbogaairportairporti",
        "esenbogaairportairport",
        "esenbogaairportankara",
        "esenbogainternationalairport",
        "ankaraesenbogainternationalairport",
    ],
    [
        "sabihagokcenairport",
        "istanbulsabihagokcenairport",
        "sabihagokcen",
        "sabihagokceninternationalairport",
        "sabihagokcenuluslararasiairport",
        "istanbulsabihagokcenuluslararasiairport",
        "sabihagokcenairportdishatlar",
        "sabihagokcendishatlar",
        "istanbulsabihagokcen",
        "istanbulsabihagokceninternationalairport",
        "sabihagokceninternetionalairport",
    ],
]

ALL_WORDS = (
    {
        "store": [
            "dollartree",
            "circlek",
            "apteka",
            "bricomarche",
            "verizon",
            "relay",
            "firestone",
            "alfamart",
            "walgreens",
            "carrefour",
            "gamestop",
            "radioshack",
            "ikea",
            "walmart",
            "7eleven",
            "bodega",
            "market",
            "boutiqu",
            "store",
            "supermarket",
            "shop",
            "grocer",
            "pharmac",
        ],
        "restaurant": [
            "warunkupnormal",
            "mado",
            "dominos",
            "solaria",
            "bistro",
            "food",
            "shawarma",
            "tearoom",
            "meatball",
            "soup",
            "breakfast",
            "bbq",
            "sushi",
            "ramen",
            "noodle",
            "burger",
            "sandwich",
            "cafe",
            "donut",
            "restaurant",
            "coffeeshop",
            "buffet",
            "pizzaplace",
            "diner",
            "steakhouse",
            "kitchen",
            "foodcourt",
            "baker",
            "starbucks",
            "dunkin",
            "tacoplac",
            "snackplac",
        ],
        "fastfood": [
            "teremok",
            "chickfil",
            "arbys",
            "popeyes",
            "chilis",
            "dairyqueen",
            "tacobell",
            "wendys",
            "burgerking",
            "fastfood",
            "kfc",
            "subway",
            "pizzahut",
            "mcdonalds",
            "friedchicken",
        ],
        "school": [
            "sororityhous",
            "fraternity",
            "college",
            "school",
            "universit",
            "classroom",
            "student",
        ],
        "housing": ["home", "housing", "residential", "building", "apartment", "condo"],
        "bank": ["creditunion", "bank", "atm"],
        "airport": [
            "baggageclaim",
            "airport",
            "terminal",
            "airline",
            "baggagereclaim",
            "concourse",
        ],
        "venue": [
            "photographystudio",
            "bowlingalle",
            "cineplex",
            "cinema",
            "ballroom",
            "stadium",
            "meetingroom",
            "conference",
            "convention",
            "entertainment",
            "venue",
            "auditorium",
            "multiplex",
            "eventspace",
            "opera",
            "concert",
            "theater",
            "megaplex",
        ],
        "museum": ["museum", "galler"],
        "church": [
            "sacred",
            "shrine",
            "spiritual",
            "mosque",
            "temple",
            "cathedral",
            "church",
            "christ",
        ],
        "park": ["zoo", "park"],
        "bar": [
            "sportclips",
            "speakeas",
            "buffalowildwing",
            "brewer",
            "pub",
            "bar",
            "nightclub",
            "nightlife",
            "lounge",
        ],
        "station": [
            "flyingj",
            "pilottravel",
            "shell",
            "bikerent",
            "rail",
            "station",
            "train",
            "metro",
            "bus",
            "stantsiia",
        ],
        "medical": [
            "poliklinika",
            "diagnos",
            "veterinarian",
            "emergencyroom",
            "hospital",
            "medical",
            "doctor",
            "dentist",
        ],
        "gym": ["clinic", "wellnes", "sportsclub", "gym", "fitnes", "athletic"],
        "outdoor": [
            "farm",
            "bagevi",
            "bridges",
            "surf",
            "dogrun",
            "sceniclookout",
            "campground",
            "golfcours",
            "forest",
            "river",
            "outdoor",
            "beach",
            "field",
            "plaza",
            "lake",
            "playground",
            "mountain",
            "pool",
            "basketballcourt",
            "garden",
        ],
        "office": [
            "techstartup",
            "hrblock",
            "work",
            "creditrepair",
            "librari",
            "coworkingspaces",
            "office",
            "service",
            "lawyer",
            "courthous",
            "cityhall",
            "notarius",
        ],
        "carrental": [
            "rentalcar",
            "hertz",
            "rentacar",
            "aviscarrent",
            "dollarrent",
            "zipcar",
            "autodealership",
            "carwashes",
        ],
        "hotel": ["boardinghous", "hostel", "hotel", "motel"],
    }
)


CAT2_DI = {
    "": 0,
    "restaurant": 1,
    "bar": 2,
    "store": 3,
    "housing": 4,
    "office": 5,
    "outdoor": 6,
    "station": 7,
    "medical": 8,
    "venue": 9,
    "hotel": 10,
    "school": 11,
    "church": 12,
    "park": 13,
    "bank": 14,
    "airport": 15,
    "gym": 16,
    "museum": 17,
    "carrental": 18,
    "fastfood": 19,
}


# median by cat2
DIST_BY_CAT_ = {
    0: 176,
    1: 61,
    2: 67,
    3: 95,
    4: 97,
    5: 90,
    6: 270,
    7: 126,
    8: 111,
    9: 121,
    10: 75,
    11: 92,
    12: 122,
    13: 205,
    14: 78,
    15: 1112,
    16: 85,
    17: 98,
    18: 59,
    19: 133,
}
# median by category_simpl
DIST_BY_CATEGORY_SIMPLE = {
    0: 135,
    1: 1108,
    2: 80,
    3: 89,
    4: 280,
    5: 52,
    6: 78,
    7: 79,
    8: 81,
    9: 153,
    10: 97,
    11: 165,
    12: 67,
    13: 95,
    14: 80,
    15: 107,
    16: 679,
    17: 65,
    18: 149,
    19: 39,
    20: 90,
    21: 100,
    22: 84,
    23: 119,
    24: 81,
    25: 84,
    26: 80,
    27: 76,
    28: 56,
    29: 143,
    30: 227,
    31: 132,
    32: 92,
    33: 31,
    34: 147,
    35: 146,
    36: 65,
    37: 70,
    38: 312,
    39: 75,
    40: 83,
    41: 64,
    42: 50,
    43: 131,
    44: 57,
    45: 71,
    46: 113,
    47: 448,
    48: 1409,
    49: 30,
    50: 273,
    51: 127,
    52: 145,
    53: 97,
    54: 68,
    55: 83,
    56: 37,
    57: 136,
    58: 5351,
    59: 97,
    60: 97,
    61: 739,
    62: 31,
    63: 66,
    64: 83,
    65: 78,
    66: 79,
    67: 87,
    68: 87,
    69: 231,
    70: 129,
    71: 612,
    72: 131,
    73: 144,
    74: 85,
    75: 111,
    76: 37,
    77: 72,
    78: 93,
    79: 361,
    80: 234,
    81: 67,
    82: 408,
    83: 109,
    84: 77,
    85: 44,
    86: 76,
    87: 88,
    88: 30,
    89: 136,
    90: 302,
    91: 152,
    92: 66,
    93: 52,
}

L1S_ID = [
    [
        "soekarnohattainternationalairport",
        "soekarnohatta",
        "soekarnohattaairport",
        "airportsoekarnohatta",
        "airportinternasionalsoekarnohatta",
        "soekarnohattainternationalairportjakarta",
        "airportsoekarnohattajakarta",
        "airportinternationalsoekarnohatta",
        "internationalairportsoekarnohatta",
        "soekarnohattaintlairport",
        "airportsoetta",
        "soettainternationalairport",
        "soekarnohattainternasionalairport",
        "soekarnohattaairport",
        "soekarnohattaairport",
        "soetta",
        "airportsukarnohatta",
        "soekarnohattaintairport",
        "soekarnohattaairportinternational",
        "soekarnohattaairportjakarta",
        "airportsoekarno",
        "jakartainternationalairportsoekarnohatta",
        "airportsoekarnohattaindonesia",
        "airportsukarnohattainternational",
        "soekarnohattainternationalairportckg",
    ],
    [
        "kualanamuinternationalairport",
        "kualanamuairport",
        "airportkualanamu",
        "kualanamuinternationalairportmedan",
        "airportinternasionalkualanamu",
        "kualanamointernationalairport",
        "airportinternationalkualanamumedan",
        "airportkualanamuinternationalairport",
        "kualanamuairportinternasional",
        "kualanamuinternasionalairportmedan",
        "kualanamuinternationl",
        "airportkualanamumedan",
        "internationalairportkualanamu",
        "kualanamuiternationalairportmedan",
        "airportkualanamumedanindonesia",
        "kualamanuinternationalairportmedan",
    ],
    [
        "ngurahraiinternationalairport",
        "ngurahraiairport",
        "igustingurahraiinternationalairport",
        "dpsngurahraiinternationalairport",
        "airportngurahraidenpasarbali",
        "ngurahraiinternationalairportairport",
        "airportngurahraiinternationalairport",
        "ngurahraiinternatioanlairportbali",
    ],
    [
        "adisuciptointernationalairport",
        "airportadisucipto",
        "adisuciptointernasionalairport",
        "airportadisuciptoyogyakarta",
        "adisutjiptoairportjogjakarta",
        "airportadisutjipto",
    ],
]
